example_app/urls.py
from django.urls import path
from example_app.views import index

app_name = 'example_app'

urlpatterns = [
    path('', index, name='index'),
]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('example_app.urls')),
    path('wishlist/', include('wishlist.urls')),
]

wishlist/urls.py
from django.urls import path
from wishlist.views import show_wishlist
from wishlist.views import show_wishlist_ajax
from wishlist.views import add_wishlist_item
from wishlist.views import show_xml
from wishlist.views import show_xml_by_id 
from wishlist.views import show_json
from wishlist.views import show_json_by_id
from wishlist.views import register
from wishlist.views import login_user
from wishlist.views import logout_user

app_name = 'wishlist'

urlpatterns = [
    path('', show_wishlist, name='show_wishlist'),
    path('ajax/', show_wishlist_ajax, name='show_wishlist_ajax'),
    path('create_data/', add_wishlist_item, name='add_wishlist_item'),
    path('xml/', show_xml, name='show_xml'),
    path('xml/<int:id>', show_xml_by_id, name='show_xml_by_id'),
    path('json/', show_json, name='show_json'),
    path('json/<int:id>', show_json_by_id, name='show_json_by_id'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
]

example_app/models.py
from django.db import models

# Create your models here.

wishlist/models.py
from django.db import models

# Create your models here.
class ItemWishlist(models.Model):
    item_name = models.CharField(max_length=50)
    item_price = models.IntegerField()
    description = models.TextField()

example_app/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'index.html')

wishlist/views.py
from django.shortcuts import render
from wishlist.models import ItemWishlist
from django.http import HttpResponse
from django.core import serializers
from django.shortcuts import redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
import datetime
from django.http import HttpResponseRedirect
from django.urls import reverse


@login_required(login_url='/wishlist/login/')
def show_wishlist(request):
    data_wishlist_item = ItemWishlist.objects.all()
    context = {
        'list_item': data_wishlist_item,
        'last_login': request.COOKIES['last_login'],
    }

    return render(request, "wishlist.html", context)

def show_wishlist_ajax(request):
    data_wishlist_item = ItemWishlist.objects.all()
    context = {
        'list_item': data_wishlist_item,
    }

    return render(request, "wishlist_ajax.html", context)

def add_wishlist_item(request):
    if request.method == 'POST':
        item_name = request.POST.get("item_name")
        item_price = request.POST.get("item_price")
        description = request.POST.get("description")

        new_barang = ItemWishlist(item_name=item_name, item_price=item_price, description=description)
        new_barang.save()

        return HttpResponse(b"CREATED", status=201)

    return HttpResponseNotFound()

def show_xml(request):
    data = ItemWishlist.objects.all()
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")


def show_xml_by_id(request, id):
    data = ItemWishlist.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")


def show_json(request):
    data = ItemWishlist.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")


def show_json_by_id(request, id):
    data = ItemWishlist.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")


def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Account successfully created!')
            return redirect('wishlist:login')
    
    context = {'form':form}
    return render(request, 'register.html', context)


def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user) # login first
            response = HttpResponseRedirect(reverse("wishlist:show_wishlist")) # create response
            response.set_cookie('last_login', str(datetime.datetime.now())) # create last_login cookie and add it to response
            return response
        else:
            messages.info(request, 'Wrong Username or Password!')
    context = {}
    return render(request, 'login.html', context)


def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('wishlist:login'))
    response.delete_cookie('last_login')
    return response

example_app/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Hello, world!</title>
{% endblock meta %}

{% block content %}
  <h1>Hello, world!</h1>
  <h3>This is example app for Django template</h3>
{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  {% block meta %}
  {% endblock meta %}
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
</head>

<body>
  <nav class="navbar navbar-expand-lg bg-light">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">Jovian | PBP Lab</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarText">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="../../">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/wishlist/">Wishlist</a>
          </li>
        </ul>
        {% if user_is_authenticated %}
        <span class="navbar-text">{{ user }}</span>
        <button type="button" class="btn btn-outline-primary"><a href="{% url 'wishlist:logout' %}">Logout</a></button>
        {% else %}
        <button type="button" class="btn btn-outline-primary"><a href="/wishlist/login">Login</a></button>
        {% endif %}        
      </div>
    </div>
  </nav>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
  {% block content %}
  {% endblock content %}
</body>

</html>

wishlist/templates/login.html
{% extends 'base.html' %}

{% block meta %}
<title>Login</title>
{% endblock meta %}

{% block content %}

<div class = "login">

    <h1>Login</h1>

    <form method="POST" action="">
        {% csrf_token %}
        <table>
            <tr>
                <td>Username: </td>
                <td><input type="text" name="username" placeholder="Username" class="form-control"></td>
            </tr>
                    
            <tr>
                <td>Password: </td>
                <td><input type="password" name="password" placeholder="Password" class="form-control"></td>
            </tr>

            <tr>
                <td></td>
                <td><input class="btn login_btn" type="submit" value="Login"></td>
            </tr>
        </table>
    </form>

    {% if messages %}
        <ul>
            {% for message in messages %}
                <li>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}     
        
    Don't have an account? <a href="{% url 'wishlist:register' %}">Create Account</a>

</div>

{% endblock content %}

wishlist/templates/register.html
{% extends 'base.html' %}

{% block meta %}
<title>Account Registration</title>
{% endblock meta %}

{% block content %}  

<div class = "login">
    
    <h1>Registration Form</h1>  

        <form method="POST" >  
            {% csrf_token %}  
            <table>  
                {{ form.as_table }}  
                <tr>  
                    <td></td>
                    <td><input type="submit" name="submit" value="Register"/></td>  
                </tr>  
            </table>  
        </form>

    {% if messages %}  
        <ul>   
            {% for message in messages %}  
                <li>{{ message }}</li>  
                {% endfor %}  
        </ul>   
    {% endif %}

</div>  

{% endblock content %}

wishlist/templates/wishlist.html
{% extends 'base.html' %}

{% block content %}

<h5>Name: </h5>
<p>{{name}}</p>

<table table class="table table-striped">
    <tr>
    <th>Item Name</th>
    <th>Item Price</th>
    <th>Description</th>
    </tr>
    {% comment %} Add data below {% endcomment %}
    {% for item in list_item %}
    	<tr>
            <td>{{item.item_name}}</td>
            <td>{{item.item_price}}</td>
            <td>{{item.description}}</td>
        </tr>
    {% endfor %}
</table>

<h5>Last Login: {{ last_login }}</h5>



{% endblock content %}

wishlist/templates/wishlist_ajax.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
  <h1>Wishlist</h1>
  <form id="form" onsubmit="return false;">
    {% csrf_token %}
    <label>Item Name</label>
    <input type="text" name="item_name"></input>
    <label>Item Price</label>
    <input type="number" name="item_price"></input>
    <label>Description</label>
    <input type="text" name="description"></input>
    <button id="button" type="submit" value="Submit" onclick="addWishlist()">Submit</button>
  </form>

  <table id="table"></table>

<script>
  async function getWishlist() {
    return fetch("{% url 'wishlist:show_json' %}").then((res) => res.json())
  }

  async function refreshWishlist() {
        document.getElementById("table").innerHTML = ""
        const wishlist = await getWishlist()
        let htmlString = `<tr>
          <th>Item Name</th>
          <th>Item Price</th>
          <th>Description</th>
        </tr>`
        wishlist.forEach((item) => {
          htmlString += `\n<tr>
          <th>${item.fields.item_name}</th>
          <th>${item.fields.item_price}</th>
          <th>${item.fields.description}</th>
        </tr>` 
        })
        
        document.getElementById("table").innerHTML = htmlString
  }

  function addWishlist() {
    fetch("{% url 'wishlist:add_wishlist_item' %}", {
          method: "POST",
          body: new FormData(document.querySelector('#form'))
      }).then(refreshWishlist)
    return false
  }

  refreshWishlist()
</script>
<h5>Last Login: {{ last_login }}</h5>
{% endblock content %}